### ISSUE TITLE
Commands not registered, Error on shutdown, Player Tags not being saved

### ISSUE THREAD

**Issue by BlackBeltPanda** [Robotv2/RobotTAGS#1]
Running RobotTags 2.1 on Purpur 1.17.1, commands don't seem to be registered. "/robottags" returns "Unknown command". Only way I could get them to work was using "/robottags:robottags".

I'm also seeing this error when players disconnect: https://pastebin.com/raw/bJVeDkD1

Also, Players have to set their color and tag every time they connect; it doesn't appear to be saving properly. Perhaps related to the error above?

**Comment by Robotv2** [comment]
First, thank you for reporting this issue. 

For the command problem, did you try using the aliases like "tag" & "tags" ?
For the mysql problem, I am now working on a fix that will be deployed on the next version. (and yes, you were right, this issues were related :) )

**Comment by BlackBeltPanda** [comment]
Yes, I tried the aliases, as well, with no luck. Using a plugin like Plugman, I was able to reload RobotTags and it registered the commands properly. However, it doesn't register the command after a server restart. Very odd behavior.

Glad to hear the MySQL issue's being fixed, thank you. =)
